### PR TITLE
Add support for \x hex escape in strings

### PR DESCRIPTION
**Pull request by meaglyn**
This provides support for up to 2 hex digits after the \x.
Unlike the in-box compiler it does not blindly consume the 2
characters following \x, which leads to problems if one of
those was the terminating ".
I chose not to make it an error if there is no following hex digit 
(unlike gcc), it just puts out the x. The inbox compile will consume
the x and the 2 following characters no matter what they are.

In all cases these escapes continue to consume the initial "\".

Also fix bogus indentation. And add a general comment to help
finding the escape code section.
[hex.nss.txt](https://github.com/nwneetools/nwnsc/files/7314106/hex.nss.txt)

hex.nss can be used to test. You can look at the pcode output to see what it does.

As before, I was doing this in my nwnnsscomp tree and figured I'd pass it along.  Do with it what you will :)

### CODE REVIEW

**Comment by meaglyn** [comment]
Oh and I have no idea if it builds on non-linux... sorry :)

**Review by jakkn — COMMENTED** [review]
Looks good to me, but I'm really not qualified to make the decision to merge. Hoping @virusman has time to give a thumbs up before we merge.

**Review by virusman — APPROVED** [review]
@meaglyn Thank you for the contribution! Sorry for the delay with the review.

**Comment by meaglyn** [comment]
@virusman  No worries. Glad it's useful.

**Pull request merged**
