### PR TITLE
add support for LOCATION_INVALID, JSON_*

### PR DESCRIPTION
**Pull request by niv**
This is just copy/pasta.

Testing level received so far: It generates bytecode for:

```
void test(json j
  = JSON_NULL
) {
  SendMessageToPC(
    GetFirstPC(),
    JsonDump(j)
  );
}

void loc(location l
  = LOCATION_INVALID
)
{

}

void main() {
  loc();
  test();
  test(JSON_FALSE);
  test(JSON_TRUE);
  test(JSON_OBJECT);
  test(JSON_ARRAY);
  test(JSON_STRING);
}
```

disasm:

```
# no .ndb found: disassembly will not show functions or metadata
     0  JSR, 8                                  
     6  RET                                     
     8  CONSTANT, TYPE_ENGST2, 0                
    14  JSR, 87                                 
    20  CONSTANT, TYPE_ENGST7, "null"           
    28  JSR, 81                                 
    34  CONSTANT, TYPE_ENGST7, "false"          
    43  JSR, 66                                 
    49  CONSTANT, TYPE_ENGST7, "true"           
    57  JSR, 52                                 
    63  CONSTANT, TYPE_ENGST7, "{}"             
    69  JSR, 40                                 
    75  CONSTANT, TYPE_ENGST7, "[]"             
    81  JSR, 28                                 
    87  CONSTANT, TYPE_ENGST7, "\"\""           
    93  JSR, 16                                 
    99  RET                                     
   101  MODIFY_STACK_POINTER, -4                
   107  RET                                     
   109  CONSTANT, TYPE_INTEGER, -1              
   115  RUNSTACK_COPY, TYPE_VOID, -8            
   123  EXECUTE_COMMAND, 969, 2                 
   128  EXECUTE_COMMAND, 548, 0                 
   133  EXECUTE_COMMAND, 374, 2                 
   138  MODIFY_STACK_POINTER, -4                
   144  RET                                     
```

### CODE REVIEW

**Comment by niv** [comment]
I've ran it for a few days testing locally and nothing is on fire yet. IMO good enough to get some wider testing.

**Comment by tinygiant98** [comment]
Been using this build on windows for a couple of weeks with no issues.  Anyone tried it on linux yet?

**Comment by squattingmonk** [comment]
Yes, I've been using it on Linux for a few months now. Not had any problems yet.

**Comment by tinygiant98** [comment]
@squattingmonk Thanks. Will see if we can push a new release soon. Still need to work string-in-case.

**Review by tinygiant98 — APPROVED** [review]
Changes have been confirmed to work on all three major operating systems (mac/win/linux).  Merging for a new release.

**Comment by tinygiant98** [comment]
Fixes #37.

**Pull request merged**
